-- Academic Archive V1.3 — multilingual interface, canonical metadata preserved
local project=require('lib.project'); local i18n=require('lib.i18n'); local stringify=pandoc.utils.stringify
local T={}; local registries={}
local function setup(meta) local I=i18n.load(i18n.meta_language(meta)); T=I.labels or {} end; local function tr(k,f) return i18n.tr(T,k,f) end
local function s(x) if x==nil then return nil end return stringify(x) end; local function esc(x) local s=tostring(x or ''); s=s:gsub('&','&amp;'):gsub('<','&lt;'):gsub('>','&gt;'):gsub('"','&quot;'); return s end
local function index(c,x) if type(x)~='table' then return end; if x.id then local id=s(x.id); local title=s(x.title) or s(x.name) or s(x.label); if id and title then registries[c..':'..id]={title=title} end end; for _,v in pairs(x) do if type(v)=='table' then index(c,v) end end end
local sources={projects='data/projects.yml',software='data/software.yml',texts='data/texts.yml',publications='data/publications.yml',supervision='data/supervision.yml',talks='data/talks.yml'}
local function build_index() registries={}; for c,p in pairs(sources) do index(c,project.yaml_meta(p)) end end
local function ref_title(ref) local r=registries[ref]; if r then return r.title end; local _,id=ref:match('^([^:]+):(.+)$'); return id or ref end
local function collection(ref) local c=ref:match('^([^:]+):'); local m={projects='collection_project',software='collection_software',texts='collection_texts',publications='collection_publication',supervision='collection_supervision',talks='collection_talk'}; return tr(m[c] or 'collection_archive',c or 'Archive') end
local function period(p) local h='<article class="archive-period"><div class="archive-period-years">'..esc(s(p.years))..'</div><h3>'..esc(s(p.title))..'</h3><p>'..esc(s(p.narrative))..'</p>'; if p.highlights and #p.highlights>0 then h=h..'<div class="archive-highlights">'; for _,x in ipairs(p.highlights) do local ref=s(x.ref); h=h..'<div class="archive-highlight"><span class="archive-dot"></span><div><strong>'..esc(ref_title(ref))..'</strong><div class="archive-small">'..esc(s(x.years))..' · '..esc(collection(ref))..'</div></div></div>' end; h=h..'</div>' end; return pandoc.RawBlock('html',h..'</article>') end
local function genealogy(g) local h='<article class="genealogy-card"><h3>'..esc(s(g.title))..'</h3><p>'..esc(s(g.summary))..'</p><div class="genealogy-flow">'; for i,n in ipairs(g.nodes or {}) do local ref=s(n.ref); if i>1 then h=h..'<span class="genealogy-arrow" aria-hidden="true">→</span>' end; h=h..'<div class="genealogy-node"><span class="genealogy-period">'..esc(s(n.period))..'</span><strong>'..esc(ref_title(ref))..'</strong><span class="genealogy-kind">'..esc(collection(ref))..'</span></div>' end; return pandoc.RawBlock('html',h..'</div></article>') end
local function H(n,x) return pandoc.Header(n,{pandoc.Str(x)}) end; local function P(x) return pandoc.Para({pandoc.Str(x)}) end
local function render(doc) build_index(); local a=project.yaml_meta('data/archive.yml'); local b={}; table.insert(b,H(2,tr('historical_trajectory','Historical Trajectory'))); table.insert(b,P(tr('historical_trajectory_intro','The archive organizes my academic trajectory as overlapping research periods.'))); for _,p in ipairs(a.periods or {}) do table.insert(b,period(p)) end; table.insert(b,H(2,tr('research_genealogies','Research Genealogies'))); table.insert(b,P(tr('research_genealogies_intro','These genealogies show long-running research continuities.'))); for _,g in ipairs(a.genealogies or {}) do table.insert(b,genealogy(g)) end; table.insert(b,H(2,tr('about_archive','About this Archive'))); table.insert(b,P(tr('about_archive_intro','This archive is evidence-based and metadata-centered.'))); for _,x in ipairs(b) do table.insert(doc.blocks,x) end; return doc end
return {{Meta=function(meta) setup(meta); return nil end},{Pandoc=render}}
