-- Supervision V1.3 — multilingual presentation over data/supervision.yml
local project=require('lib.project'); local i18n=require('lib.i18n'); local stringify=pandoc.utils.stringify
local I,T={},{}
local function setup(meta) I=i18n.load(i18n.meta_language(meta)); T=I.labels or {} end; local function tr(k,f) return i18n.tr(T,k,f) end
local function text(v) if v==nil then return '' end return stringify(v) end
local function name(r) return r.student and r.student.name and text(r.student.name) or '' end
local function year(r) return r['end'] and (tonumber(text(r['end'])) or 0) or 0 end
local function url(r) return r.thesis and r.thesis.persistent_url and text(r.thesis.persistent_url)~='' and text(r.thesis.persistent_url) or nil end
local function topics(r) local a={}; for _,x in ipairs(r.topics or {}) do local k=text(x); table.insert(a,i18n.tr(I.supervision_topic_labels,k,k)) end; return a end
local function select(rs,level,status) local a={}; for _,r in ipairs(rs) do if text(r.level)==level and text(r.status)==status then table.insert(a,r) end end; table.sort(a,function(x,y) if status=='current' then return name(x):lower()<name(y):lower() end; if year(x)~=year(y) then return year(x)>year(y) end; return name(x):lower()<name(y):lower() end); return a end
local function current_card(r,label) local b={pandoc.Header(3,pandoc.Str(name(r))),pandoc.Para({pandoc.Strong({pandoc.Str(label)}),pandoc.Str(' · Universidade Federal de Santa Catarina')})}; if text(r.title)~='' then table.insert(b,pandoc.Para({pandoc.Emph({pandoc.Str(text(r.title))})})) end; local ts=topics(r); if #ts>0 then local x={}; for n,t in ipairs(ts) do if n>1 then table.insert(x,pandoc.Str(' · ')) end; table.insert(x,pandoc.Str(t)) end; table.insert(b,pandoc.Para(x)) end; return pandoc.Div(b,pandoc.Attr('',{'supervision-card'})) end
local function item(r) local x={pandoc.Strong({pandoc.Str(name(r))})}; if year(r)>0 then table.insert(x,pandoc.Str(' ('..year(r)..')')) end; if text(r.title)~='' then table.insert(x,pandoc.Str(' — ')); table.insert(x,pandoc.Emph({pandoc.Str(text(r.title))})) end; local u=url(r); if u then local k=text(r.level)=='phd' and 'dissertation' or (text(r.level)=='masters' and 'masters_thesis_link' or 'academic_work'); table.insert(x,pandoc.Str(' · ')); table.insert(x,pandoc.Link({pandoc.Str(tr(k,'Academic work'))},u)) end; return {pandoc.Plain(x)} end
local function current(rs,level,title,student) local a=select(rs,level,'current'); local b={pandoc.Header(2,pandoc.Str(title..' ('..#a..')'))}; if #a==0 then table.insert(b,pandoc.Para({pandoc.Emph({pandoc.Str(tr('no_current_students','No current students listed.'))})})); return b end; local cards={}; for _,r in ipairs(a) do table.insert(cards,current_card(r,student)) end; table.insert(b,pandoc.Div(cards,pandoc.Attr('',{'supervision-grid'}))); return b end
local function completed(rs,level,title) local a=select(rs,level,'completed'); local b={pandoc.Header(2,pandoc.Str(title..' ('..#a..')'))}; if #a==0 then table.insert(b,pandoc.Para({pandoc.Emph({pandoc.Str(tr('no_completed_supervisions','No completed supervisions listed.'))})})); return b end; if level=='phd' then local it={}; for _,r in ipairs(a) do table.insert(it,item(r)) end; table.insert(b,pandoc.BulletList(it)); return b end
 local periods={{'2020–2026',2020,2026,{}},{'2010–2019',2010,2019,{}},{'2000–2009',2000,2009,{}},{tr('before_2000','Before 2000'),0,1999,{}}}; local unknown={}; for _,r in ipairs(a) do local y=year(r); local placed=false; if y>0 then for _,p in ipairs(periods) do if y>=p[2] and y<=p[3] then table.insert(p[4],r); placed=true; break end end end; if not placed then table.insert(unknown,r) end end
 for _,p in ipairs(periods) do if #p[4]>0 then table.insert(b,pandoc.RawBlock('html','<details class="supervision-period"><summary>'..p[1]..' <span class="supervision-count">('..#p[4]..')</span></summary>')); local it={}; for _,r in ipairs(p[4]) do table.insert(it,item(r)) end; table.insert(b,pandoc.BulletList(it)); table.insert(b,pandoc.RawBlock('html','</details>')) end end
 if #unknown>0 then table.insert(b,pandoc.RawBlock('html','<details class="supervision-period"><summary>'..tr('year_to_verify','Year to be verified')..' <span class="supervision-count">('..#unknown..')</span></summary>')); local it={}; for _,r in ipairs(unknown) do table.insert(it,item(r)) end; table.insert(b,pandoc.BulletList(it)); table.insert(b,pandoc.RawBlock('html','</details>')) end; return b end
local function append(a,b) for _,x in ipairs(b) do table.insert(a,x) end end
local function div(el) if not el.classes:includes('supervision-generated') then return nil end; local m=project.yaml_meta('data/supervision.yml'); if not m or not m.supervisions then return pandoc.Div({pandoc.Para({pandoc.Strong({pandoc.Str(tr('unable_load_supervision','Unable to load supervision data.'))})})}) end; local r=m.supervisions; local b={}; append(b,current(r,'phd',tr('current_phd_students','Current PhD Students'),tr('phd_student','PhD student'))); append(b,current(r,'masters',tr('current_masters_students',"Current Master's Students"),tr('masters_student',"Master's student"))); append(b,completed(r,'phd',tr('former_phd_students','Former PhD Students'))); append(b,completed(r,'masters',tr('former_masters_students',"Former Master's Students"))); return pandoc.Div(b) end
return {{Meta=function(meta) setup(meta); return nil end},{Div=div}}
