-- Teaching V1.3 — multilingual presentation over data/teaching.yml
local project=require('lib.project'); local i18n=require('lib.i18n'); local stringify=pandoc.utils.stringify
local I,T={},{}
local function setup(meta) I=i18n.load(i18n.meta_language(meta)); T=I.labels or {} end
local function tr(k,f) return i18n.tr(T,k,f) end
local function str(v) if v==nil then return '' end return stringify(v) end
local function esc(s) s=tostring(s or ''); s=s:gsub('&','&amp;'):gsub('<','&lt;'):gsub('>','&gt;'):gsub('"','&quot;'); return s end
local function bool(v) return v==true or str(v)=='true' end
local function level(v) local x=str(v); return tr(x:gsub('-','_'),x) end
local function topic(v) local x=str(v); return i18n.tr(I.teaching_topic_labels,x,x) end
local function offering_map(d) local m={}; for _,o in ipairs(d.offerings or {}) do local id=str(o.course_id); m[id]=m[id] or {}; table.insert(m[id],o) end; return m end
local function cards(d) local om=offering_map(d); local h={'<div class="teaching-grid">'}; for _,c in ipairs(d.courses or {}) do if bool(c.featured) then table.insert(h,'<article class="teaching-card">'); local code=c.code and '<span class="teaching-code">'..esc(str(c.code))..'</span>' or ''; table.insert(h,'<div class="teaching-card-head">'..code..'<span class="teaching-level">'..esc(level(c.level))..'</span></div>'); table.insert(h,'<h3>'..esc(str(c.public_title or c.title))..'</h3>'); if c.official_title and c.public_title then table.insert(h,'<p class="teaching-official">'..esc(str(c.official_title))..'</p>') end; table.insert(h,'<p>'..esc(str(c.summary))..'</p>'); local offs=om[str(c.id)] or {}; if #offs>0 then local terms={}; for _,o in ipairs(offs) do table.insert(terms,esc(str(o.term))) end; table.insert(h,'<p class="teaching-meta"><strong>'..esc(tr('documented_offerings','Documented offerings'))..':</strong> '..table.concat(terms,', ')..'</p>') end; if c.topics and #c.topics>0 then table.insert(h,'<div class="teaching-tags">'); for _,t in ipairs(c.topics) do table.insert(h,'<span>'..esc(topic(t))..'</span>') end; table.insert(h,'</div>') end; table.insert(h,'</article>') end end; table.insert(h,'</div>'); return table.concat(h,'\n') end
local function resources(d) local names={['course-program']=tr('course_programs','Course programs'),['teaching-plan']=tr('teaching_plans','Teaching plans'),assessment=tr('assessments','Assessments'),exam=tr('exams','Exams')}; local order={'course-program','teaching-plan','assessment','exam'}; local by={}; for _,m in ipairs(d.materials or {}) do local x=str(m.type); by[x]=by[x] or {}; table.insert(by[x],m) end; local h={}; for _,typ in ipairs(order) do if by[typ] then table.insert(h,'<div class="teaching-resource-group"><h3>'..esc(names[typ])..'</h3><ul>'); for _,m in ipairs(by[typ]) do local vis=str(m.visibility_candidate); local badge=vis=='public' and tr('public_candidate','public candidate') or tr('review_before_publication','review before publication'); local label=str(m.topic); if label=='' then label=str(m.date_or_term) end; if label=='' then label=str(m.date) end; if label=='' then label=str(m.id) end; table.insert(h,'<li><strong>'..esc(label)..'</strong> <span class="teaching-status">'..esc(badge)..'</span></li>') end; table.insert(h,'</ul></div>') end end; return table.concat(h,'\n') end
local function history(d) local h={'<div class="teaching-history-list">'}; for _,x in ipairs(d.historical_courses_from_lattes or {}) do table.insert(h,'<div class="teaching-history-item">'..esc(str(x))..'</div>') end; table.insert(h,'</div>'); return table.concat(h,'\n') end
local function div(el) local d=project.yaml_meta('data/teaching.yml'); if el.identifier=='teaching-current' then return pandoc.RawBlock('html',cards(d)) elseif el.identifier=='teaching-resources' then return pandoc.RawBlock('html',resources(d)) elseif el.identifier=='teaching-history' then return pandoc.RawBlock('html',history(d)) end; return nil end
return {{Meta=function(meta) setup(meta); return nil end},{Div=div}}
