-- Books & Texts V1.3 — multilingual presentation over data/texts.yml
local project=require('lib.project'); local i18n=require('lib.i18n'); local stringify=pandoc.utils.stringify
local T={}; local function setup(meta) local I=i18n.load(i18n.meta_language(meta)); T=I.labels or {} end; local function tr(k,f) return i18n.tr(T,k,f) end
local function esc(s) s=tostring(s or ''); s=s:gsub('&','&amp;'):gsub('<','&lt;'):gsub('>','&gt;'):gsub('"','&quot;'); return s end
local function value(x) if x==nil then return nil end return stringify(x) end
local function join(a) local r={}; for _,v in ipairs(a or {}) do table.insert(r,stringify(v)) end; return table.concat(r,', ') end
local function badge(x,c) return '<span class="text-badge '..c..'">'..esc(x)..'</span>' end
local function evidence(w) local e=value(w.evidence_status) or ''; local s=value(w.status) or ''; if s=='identified' then return badge(tr('document_identified','Document identified'),'evidence-identified') end; if e=='externally-corroborated' then return badge(tr('externally_corroborated','Externally corroborated'),'evidence-corroborated') end; if e=='institutionally-contextualized' then return badge(tr('institutional_context','Institutional context'),'evidence-context') end; if e=='academically-contextualized' then return badge(tr('academic_context','Academic context'),'evidence-context') end; if e=='project-contextualized' then return badge(tr('project_context','Project context'),'evidence-context') end; return badge(tr('bibliographic_record_text','Bibliographic record'),'evidence-record') end
local function typ(x) local m={book='book',['book-chapter']='book_chapter',commentary='commentary',['technical-report']='technical_report',['scientific-text']='scientific_text',['teaching-material']='teaching_material'}; return tr(m[x] or x,x) end
local function cite(w) local b={}; if w.publisher then table.insert(b,esc(value(w.publisher))) end; if w.container then table.insert(b,esc(value(w.container))) end; if w.place then table.insert(b,esc(value(w.place))) end; if w.volume then table.insert(b,'vol. '..esc(value(w.volume))) end; if w.pages then table.insert(b,esc(value(w.pages))..' pp.') end; if w.isbn then table.insert(b,'ISBN '..esc(value(w.isbn))) end; return table.concat(b,' · ') end
local function card(w) local t=value(w.type) or 'text'; local h='<article class="text-work"><div class="text-work-top"><div><h3>'..esc(value(w.title))..'</h3>'; local a=join(w.authors); if a~='' then h=h..'<div class="text-authors">'..esc(a)..'</div>' end; h=h..'</div><div class="text-year">'..esc(value(w.year) or '')..'</div></div><div class="text-meta">'..badge(typ(t),'type-badge')..evidence(w)..'</div>'; local c=cite(w); if c~='' then h=h..'<div class="text-citation">'..c..'</div>' end; return pandoc.RawBlock('html',h..'</article>') end
local function sort(a,b) local ay=tonumber(value(a.year)) or 0; local by=tonumber(value(b.year)) or 0; if ay~=by then return ay>by end; return (value(a.title) or '')<(value(b.title) or '') end
local function select(ws,types,pred) local set={}; for _,t in ipairs(types) do set[t]=true end; local r={}; for _,w in ipairs(ws) do if set[value(w.type)] and (not pred or pred(w)) then table.insert(r,w) end end; table.sort(r,sort); return r end
local function section(b,title,intro,items) table.insert(b,pandoc.Header(2,{pandoc.Str(title)})); if intro then table.insert(b,pandoc.Para({pandoc.Str(intro)})) end; for _,w in ipairs(items) do table.insert(b,card(w)) end end
local function render(doc) local m=project.yaml_meta('data/texts.yml'); local ws=m.works or {}; local b={}; section(b,tr('books','Books'),tr('books_intro','Books and longer-form works authored or co-authored by Ricardo Custódio.'),select(ws,{'book'})); section(b,tr('book_chapters_commentary','Book Chapters & Commentary'),tr('book_chapters_commentary_intro','Selected chapters and commentary.'),select(ws,{'book-chapter','commentary'})); local rec=select(ws,{'technical-report','scientific-text'},function(w) return value(w.status)=='identified' end); if #rec>0 then section(b,tr('technical_scientific_texts','Technical & Scientific Texts'),tr('technical_scientific_texts_intro','Technical and scientific texts for which a document has already been identified.'),rec) end; section(b,tr('teaching_materials','Teaching Materials'),tr('teaching_materials_intro','Teaching-oriented texts and instructional material preserved as part of the academic record.'),select(ws,{'teaching-material'})); local hist=select(ws,{'technical-report','scientific-text'},function(w) return value(w.status)~='identified' end); table.insert(b,pandoc.Header(2,{pandoc.Str(tr('historical_archive','Historical Archive'))})); table.insert(b,pandoc.Para({pandoc.Str(tr('historical_texts_intro','Historical technical and scientific texts identified in the academic record.'))})); if #hist>0 then local inner={}; for _,w in ipairs(hist) do table.insert(inner,card(w)) end; table.insert(b,pandoc.Div(inner,pandoc.Attr('',{'historical-texts'}))) end; for _,x in ipairs(b) do table.insert(doc.blocks,x) end; return doc end
return {{Meta=function(meta) setup(meta); return nil end},{Pandoc=render}}
